### ISSUE TITLE
能迁移到空安全吗？

### ISSUE THREAD

**Issue by gionlime** [persilee/flutter_pro#5]
能迁移到空安全吗？

**Comment by persilee** [comment]
暂时，没时间迁移到空安全，以后的新项目都会使用2.0的flutter的空安全

**Comment by persilee** [comment]
暂时，没时间迁移到空安全，以后的新项目都会使用2.0的flutter的空安全

> 

暂时，没时间迁移到空安全，以后的新项目都会使用2.0的flutter的空安全
